### ISSUE TITLE
Checkstyle fails with Gradle 3.5

### ISSUE THREAD

**Issue by dturanski** [reactor/reactor-kafka#16]
I have Gradle 3.5 installed.  After running `gradle wrapper` , `./gradlew test` fails with lots of

```
[ant:checkstyle] [ERROR] /Users/dturanski/dev/reactor-kafka/src/main/java/reactor/kafka/receiver/internals/DefaultKafkaReceiver.java:143: 'block' child have incorrect indentation level 24, expected level should be 20. [Indentation]
``` 
```
$./gradlew version
------------------------------------------------------------
Gradle 3.5
------------------------------------------------------------

Build time:   2017-04-10 13:37:25 UTC
Revision:     b762622a185d59ce0cfc9cbc6ab5dd22469e18a6

Groovy:       2.4.10
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_60 (Oracle Corporation 25.60-b23)
OS:           Mac OS X 10.12.6 x86_64
```

After downgrading to Gradle 2.13 and rerun `gradle wrapper` it works.

**Comment by ilayaperumalg** [comment]
Hi @dturanski , It turns out running `gradle wrapper` is counterproductive as `./gradlew` would work just fine with the supported version. We also [removed](https://github.com/reactor/reactor-kafka/commit/b99af78c1ffeda1a65841398e932f08061a5acbf) that specific section that mentions about `downloading and installing gradle wrapper` from the README.

Thank you for bringing this up.
