### ISSUE TITLE
The reference is incorrectly formatted and this messes up the index and the titles. 

### ISSUE THREAD

**Issue by sambiak** [reactor/reactor-kafka#241]
## Documentation Issue
 The section : *What’s new in Reactor Kafka 1.2.0.RELEASE* should be indexed at 5.4 and the next section should be reference. 
Instead the section 6 is *What’s new in Reactor Kafka 1.2.0.RELEASE* and the *Reactor Kafka API* sections are shown as subsections of this same subsection.

![image](https://user-images.githubusercontent.com/7650026/134017713-4e50a84d-533e-4111-9bc2-82f506163628.png)

## Improvement Suggestion
Add an = to line 24 of `new.adoc`, although more may be needed to fix the formatting, I'm not familiar with adoc.

## Additional context
The issue can be seen at https://projectreactor.io/docs/kafka/release/reference/ and https://projectreactor.io/docs/kafka/snapshot/reference/

**Comment by simonbasle** [comment]
Thanks for raising this @sambiak. We can actually see what should have been top-level toc entries in the body of paragraph 6 in your screenshot (`= Reference Documentation`)...

The section "New and noteworthy" hasn't been updated in a while and isn't really useful at all, compared to the [notes from Github releases](https://github.com/reactor/reactor-kafka/releases). It should therefore be removed.

We could do that in branch 1.2.x, although we're not likely to release `reactor-kafka` just for that change. Since it is "only" a formatting break, we could also just do that in `main` branch.

The fastest way to do that is by removing the `new.adoc` include in `index.asciidoc` and delete the file.
I think that the formatting issue would probably disappear once this is done.

Do you want to submit a PR @sambiak ?

**Comment by sambiak** [comment]
Sure why not, I'll do it this evening. I'll be

**Comment by sambiak** [comment]
Sorry about that missclicked. Sure why not I'll do it this evening after work.

**Comment by AndersClausen** [comment]
@sambiak did you create a PR for this or should I do it? Cheers

**Comment by simonbasle** [comment]
> @sambiak did you create a PR for this or should I do it? Cheers

@AndersClausen there has been no news from @sambiak so please go ahead and take this one if you have some availability
