### ISSUE TITLE
Defer Out-of-Order Commits

### ISSUE THREAD

**Issue by garyrussell** [reactor/reactor-kafka#243]
Similar to https://docs.spring.io/spring-kafka/docs/2.8.0-SNAPSHOT/reference/html/#x28-ooo-commits

**Comment by aaaaaaaaaam** [comment]
Hey. Any new with this? Any workaround meanwhile until it's being implemented? I cannot use the Spring Kafka solution, but I wonder if there's another workaround for the reactive kafka users.

**Comment by garyrussell** [comment]
No progress yet. You will have to track the offsets yourself and make sure that they are committed in order.

**Comment by aaaaaaaaaam** [comment]
OK, thanks. Is there any plan of implementing it in the near future? If yes, can you approximately tell when it would be ready?

I thought about implementing a thread-safe queue that each consumer of a partition will manage. Each message will be written to that queue only after its process is finished, and another thread will read the queue, and commit only if there is no missing offset. The first offset of the queue will always be the last offset of the most recent commit. Do you think that this implementation direction will fit?

**Comment by garyrussell** [comment]
I will take a look at it next week; it will probably be similar to what I did in Spring for Apache Kafka. When a gap is filled for a partition, all offsets up to the next gap are committed.

https://github.com/spring-projects/spring-kafka/pull/1860

**Comment by aaaaaaaaaam** [comment]
Thank you. But how would you know if there's a gap and which messages to commit? Don't you manage some thread-safe queue with a reader that reads the queue repeatedly?

**Comment by garyrussell** [comment]
Internally, there is a single threaded scheduler that interacts with the `Consumer`; it will maintain a list of unack'd offsets; yes, it's sort-of a queue (for each partition) with the head being the first uncommitted offset. 

Then when the user code commits an offset, it will be stored in a pending offsets collection (if there is a gap); if there is not a gap, all pending offsets will be committed up to the next gap.

It's easier to do it there since it is single-threaded. It's harder to do it at the application level because of multi-threading and you don't easily have access to the first uncommitted offset(s) - you'd have to figure that out some other way.

**Comment by aaaaaaaaaam** [comment]
So you're saying that internally the Reactor-Kafka implementation managed a single thread interacts with the Kafka brokers? And thus it's easier to implement the logic there because there is only a need for reading the queue for each partition and seeing if there is a gap so we'll commit until there?

**Comment by garyrussell** [comment]
Correct.

**Comment by aaaaaaaaaam** [comment]
Hey @garyrussell , Is there any plans for implementing this in Reactor Kafka? My company is about to write a very large software that is based on Reactive Spring Cloud Stream so we would be very glad for any news in the subject. I want to know if I need to implement it myself or if in the near future it is planned to be implemented.

**Comment by garyrussell** [comment]
@aaaaaaaaaam - as I said above https://github.com/reactor/reactor-kafka/issues/243#issuecomment-982823342 I will look at it this week.

**Comment by garyrussell** [comment]
I have it working - I need to add some more tests; I should have a pull request tomorrow.

**Comment by aaaaaaaaaam** [comment]
Awesome. Thank you for the quick response

**Comment by aaaaaaaaaam** [comment]
Just to be sure, is it thread-safe? Can I commit from many threads in parallel at the same time and Reactor-Kafka will manage the order with sort of synchronization\ locks? Or do I need to commit from one thread but it just can be out of order? 
Also, I have the same question about Spring-Kafka.

**Comment by garyrussell** [comment]
Yes, it is thread safe (both projects).

**Comment by polrsg** [comment]
Hi @garyrussell ! 
I want to use the out-of-order commits (to be able to group-by messages from the same partition, process them in parallel and then acknowledge each message when the process is finished).

I read in the documentation that `kafkaReceiver` is not thread-safe as mention below:   
![kafka-receiver](https://user-images.githubusercontent.com/103367384/162618906-9bd086e2-c436-4a66-9a85-fb59565cb20c.png)

and I also read that you commented to @aaaaaaaaaam that it is safe to use `ReciverOffset.acknowledge()` from many threads in concurrency (in my case I want the threads that processes each group of the partition to acknowledge). Is it possible because the `reactor.kafka.reciver.ReceiverOffset` class is thread safe? (I guess `ReceiverOffset` is using `KafkaConsumer` under the hood which is not thread safe). Am I missing something? the documentation confuses me a little bit

**Comment by garyrussell** [comment]
@polrsg this has nothing to do with the thread safety of the consumer or receiver; I made the `CommittableBatch` implementation for the out of order commit logic thread safe for just this use case.
