### ISSUE TITLE
snappy-java-1.1.8.4.jar (pkg:maven/org.xerial.snappy/snappy-java@1.1.8.4) : CVE-2023-34455, CVE-2023-34453 

### ISSUE THREAD

**Issue by patpatpat123** [reactor/reactor-kafka#348]
## Expected Behavior
Reactor Kafka should contain a "safe" version of snappy java and not a vulnerable one if possible.

## Actual Behavior
[INFO] --- maven-dependency-plugin:3.5.0:tree (default-cli) @ myprojectwithreactorkafka---
[INFO] com.:myprojectwithreactorkafka:jar:1.1
[INFO] +- io.projectreactor.kafka:reactor-kafka:jar:1.3.18:compile
[INFO] |  +- io.projectreactor:reactor-core:jar:3.5.6:compile
[INFO] |  |  \- org.reactivestreams:reactive-streams:jar:1.0.4:compile
[INFO] |  \- org.apache.kafka:kafka-clients:jar:3.4.0:compile
[INFO] |     +- com.github.luben:zstd-jni:jar:1.5.2-1:runtime
[INFO] |     +- org.lz4:lz4-java:jar:1.8.0:runtime
[INFO] |     \- org.xerial.snappy:snappy-java:jar:1.1.8.4:runtime

This version is vulnerable: CVE-2023-34455, CVE-2023-34453 

## Steps to Reproduce
Just need to pull the latest version of reactor kafka. It will pull the vulnerable version of snappy.

## Possible Solution
Could you please help bump to a safe version of snappy, such as

```
<!--        <dependency>-->
<!--            <groupId>org.xerial.snappy</groupId>-->
<!--            <artifactId>snappy-java</artifactId>-->
<!--            <version>1.1.10.1</version>-->
<!--        </dependency>-->
```

## Your Environment
SpringBoot 3.1.0 and the latest reactor kafka

* Reactor version(s) used: 
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`java -version`): GraalVM 17
* OS and version (eg `uname -a`): Reproducible with all OS

**Comment by artembilan** [comment]
> `snappy-java` is a Java port of the `snappy`, a fast C++ compresser/decompresser developed by Google.

This project doesn't use that API directly. It comes transitively from `kafka-clients`.
And looks like even their latest version comes with a vulnerable `snappy-java`: https://mvnrepository.com/artifact/org.apache.kafka/kafka-clients/3.5.0.

I think it is more correct to ask Apache Kafka project to fix that dependency. 
Even if vulnerability report shows you exactly this `reactor-kafka` project, I believe it is more informative purpose rather than call for action exactly in this project.
Do you anticipate many other `kafka-clients` users (e.g. `spring-kafka`) to fix that dependency for you?
Why it is not just better to fix it once exactly in that `kafka-clients` where this `snappy-java` is an explicit dependency?

Closed as `Works as Designed`

**Comment by patpatpat123** [comment]
Thank you for the clear explanation. I wish I could just open an issue on Apache Kafka. Good to close

**Comment by garyrussell** [comment]
>I wish I could just open an issue on Apache Kafka. 

https://issues.apache.org/jira/projects/KAFKA/summary

Or start a discussion on their user mailing list.
