### ISSUE TITLE
Allow SenderRecord to take into account existing Observation

### ISSUE THREAD

**Issue by patpatpat123** [reactor/reactor-kafka#373]
## Motivation
As of today, after the positive work from PR325, it is possible to pass in Observation to reactor kafka.
On a very simple use case: "publish to topic B what got received from topic A" represented by the code below:

```
    Flux<SenderResult<String>> reactorKafkaPropagatesTraces() {
        return kafkaSender.send(
                this.kafkaReceiver
                        .receive()
                        .flatMap(record -> {
                            return Mono.just(record)
                                    .map(oneReceivedMessage -> {
                                        String transformedMessage = oneReceivedMessage.value();
                                        LOGGER.info("I WOULD LIKE TO SEE DIFFERENT TRACES HERE AS WELL PLEASE" + transformedMessage);
                                        return transformedMessage.toUpperCase();
                                    });
                        })
                        .map(oneTransformedReceivedMessage -> SenderRecord.create(new ProducerRecord<>("TOPIC_DESTINATION", null, oneTransformedReceivedMessage), oneTransformedReceivedMessage))
                )
                ;
    }
```

It would be great to allow the sender to take into account existing Observation, so each message of the flux can have its own trace.
For instance, the flux has many messages, the trace for the first message would be [aaa,111] the trace for the second message would be [bbb,222], the trace for the third message would be [ccc,333] etc etc etc

As of right now, this code:

```
return 
                this.kafkaReceiver
                        .receive()
                        .flatMap(record -> {
                            Observation receiverObservation =
                                    KafkaReceiverObservation.RECEIVER_OBSERVATION.start(null,
                                            KafkaReceiverObservation.DefaultKafkaReceiverObservationConvention.INSTANCE,
                                            () -> new KafkaRecordReceiverContext(record, "user.receiver", "myKafkaServer"),
                                            this.observationRegistry);

                            return Mono.just(record)
                                    .map(oneReceivedMessage -> {
                                        String transformedMessage = oneReceivedMessage.value();
                                        LOGGER.info("I WOULD LIKE TO SEE DIFFERENT TRACES HERE AS WELL PLEASE" + transformedMessage);
                                        return transformedMessage.toUpperCase();
                                    })
                                    .tap(Micrometer.observation(observationRegistry))
                                    .doOnTerminate(receiverObservation::stop)
                                    .doOnError(receiverObservation::error)
                                    .contextWrite(context -> context.put(ObservationThreadLocalAccessor.KEY, receiverObservation));
```

Would yield for the first message [aaa,111] the trace for the second message would be [bbb,222], the trace for the third message would be [ccc,333] etc etc etc

However, the kafka sender is absent.

Now adding the kafka sender with code as follow:

```
Flux<SenderResult<String>> reactorKafkaPropagatesTraces() {
        return kafkaSender.send(
                this.kafkaReceiver
                        .receive()
                        .flatMap(record -> {
                            Observation receiverObservation =
                                    KafkaReceiverObservation.RECEIVER_OBSERVATION.start(null,
                                            KafkaReceiverObservation.DefaultKafkaReceiverObservationConvention.INSTANCE,
                                            () -> new KafkaRecordReceiverContext(record, "user.receiver", "myKafkaServer"),
                                            this.observationRegistry);

                            return Mono.just(record)
                                    .map(oneReceivedMessage -> {
                                        String transformedMessage = oneReceivedMessage.value();
                                        LOGGER.info("I WOULD LIKE TO SEE DIFFERENT TRACES HERE AS WELL PLEASE" + transformedMessage);
                                        return transformedMessage.toUpperCase();
                                    })
                                    .tap(Micrometer.observation(observationRegistry))
                                    .doOnTerminate(receiverObservation::stop)
                                    .doOnError(receiverObservation::error)
                                    .contextWrite(context -> context.put(ObservationThreadLocalAccessor.KEY, receiverObservation));
                        })
                        .map(oneTransformedReceivedMessage -> SenderRecord.create(new ProducerRecord<>("CHANGE_TOPIC_DESTINATION", null, oneTransformedReceivedMessage), oneTransformedReceivedMessage))
                )
                ;
    }
```

This would yield the incorrect result:

first message would get [aaa,111]
second message would get [aaa,222]
third message would get [aaa,333]

## Desired solution

Would it be possible to enhance the API in order to allow the sender to take into account the context?
Something like 
```
.map(oneTransformedReceivedMessage -> 

SenderRecord.create(new ProducerRecord<>("CHANGE_TOPIC_DESTINATION", null, oneTransformedReceivedMessage), oneTransformedReceivedMessage), Observation)
```

Thank you

**Comment by patpatpat123** [comment]
@chemicL Please let me know if my description is not clear enough, and apologies in advanced for that

**Comment by chemicL** [comment]
@patpatpat123 I'm not certain whether the result of [aaa,111], [aaa,222], [aaa,333] is accurate and whether you mean it comes from the logs performed upon the received events or whether these are the spans that would arrive in the producer.

I think in general the inquiry is about the inversion of control.

Assuming the use case of "for each received record, I'd like to send a new record derived from the received one", the natural way of expressing this (at least in my head) would be along these lines:

```
                this.kafkaReceiver
                        .receive()
                        .flatMap(record -> {
                            Observation receiverObservation = ...; // extract from record

                            return kafkaSender.send( // received record used to send a derived message
                                    Mono.just(record)
                                        .map(this::transform) 
                                        .tap(Micrometer.observation(observationRegistry))
                                        .map(r -> SenderRecord.create(new ProducerRecord<>("B", null, r), r))
                                        .doOnTerminate(receiverObservation::stop)
                                        .doOnError(receiverObservation::error)
                                        .contextWrite(context -> context.put(ObservationThreadLocalAccessor.KEY, receiverObservation)));
                        });
```

and that allows the sender to take advantage of the `receiverObservation` to make it the parent of the newly sent record's `Observation`, therefore establishing the relationship.

However, due to performance concerns, the following is used:

```
        kafkaSender.send( // send wraps the transformed receiver flux
                this.kafkaReceiver
                        .receive()
                        .flatMap(record -> {
                            Observation receiverObservation = ...; // extract from record

                            return Mono.just(record)
                                    .map(this::transform)
                                    .tap(Micrometer.observation(observationRegistry))
                                    .doOnTerminate(receiverObservation::stop)
                                    .doOnError(receiverObservation::error)
                                    .contextWrite(context -> context.put(ObservationThreadLocalAccessor.KEY, receiverObservation));
                        })
                        .map(r -> SenderRecord.create(new ProducerRecord<>("B", null, r), r))
                );
```

The problem now is that the `receiverObservation` is confined to the lambda of the `flatMap`. If the `SenderRecord` allowed to provide the parent `Observation`, it would allow the `Observation` to be passed to the outside of the `flatMap` (for instance using a `Tuple2`) and be provided for the sent record.

The major issue here is that now the observability aspect becomes part of the business logic. However, it already is surfacing unfortunately, due to the limits of the existing API. The API can be further enhanced in the future by providing record transformers, to which an Observation would be transparently attached. Yet, I think what @patpatpat123 would like to understand here is how to achieve the performance and still maintain the correlation between the received message and the sent message.

**Comment by patpatpat123** [comment]
Yes, correct, thank you for the clarification

**Comment by artembilan** [comment]
I'm not sure what is your business goal and how you ready to break it, but looks like there is misunderstanding how things works.
The `Observation` we go inside a `flatMap()` from receiver is available only for those operators in `Mono` which comes before `contextWrite`.
When we just outside of this `flatMap()` to the next top-level operator that context is lost. 
Therefore one of the solutions is to return `Tuple2` as @chemicL suggested and then that extracted observation will be available in downstream top-level operators.
This solution has a drawback since both possible child observation in your `.map(this::transform)` and that `.map(r -> ` would be siblings for the same parent observation you have just extracted from the record in `flatMap`.


Another solution I may suggest as to use `KafkaOutbound.send().then()` somewhere there in the `Mono` within that `flatMap` instead.
See `KafkaSender.createOutbound()`.
This way the `contextWrite` scope will be satisfied and producer record observation becomes a child span of the consumer record's.

Does that makes sense?

**Comment by patpatpat123** [comment]
Thank you @artembilan for the answer.

I would like to focus on your first proposed solution.

As of today, in 1.3.22, even if I use the Tuple2 construct, it seems the extracted observation is still not available to downstream top-level operators.

For instance, suppose I have the Tuple2, where one of the elements is the Observation, the send operation in its current form does not allow the Observation present to be passed. am I correct?

**Comment by patpatpat123** [comment]
Here is the snippet with Tuples. 
The send does not allow to take into account the Tuples.getT2(), aka the Observation.
Am I correct?

```
Flux<SenderResult<String>> reactorKafkaPropagatesTraces() {
        return kafkaSender.send(
                this.kafkaReceiver
                        .receive()
                        .flatMap(record -> {
                            Observation receiverObservation =
                                    KafkaReceiverObservation.RECEIVER_OBSERVATION.start(null,
                                            KafkaReceiverObservation.DefaultKafkaReceiverObservationConvention.INSTANCE,
                                            () -> new KafkaRecordReceiverContext(record, "user.receiver", "myKafkaServer"),
                                            this.observationRegistry);

                            return Mono.just(record)
                                    .map(oneReceivedMessage -> {
                                        String transformedMessage = oneReceivedMessage.value();
                                        LOGGER.info("I WOULD LIKE TO SEE DIFFERENT TRACES HERE AS WELL PLEASE" + transformedMessage);
                                        return Tuples.of(transformedMessage.toUpperCase(), receiverObservation); // change here, to return the tuple2 with Observation in .getRight() .getT2()
                                    })
                                    .tap(Micrometer.observation(observationRegistry))
                                    .doOnTerminate(receiverObservation::stop)
                                    .doOnError(receiverObservation::error)
                                    .contextWrite(context -> context.put(ObservationThreadLocalAccessor.KEY, receiverObservation));
                        })
                        //I cannot pass in oneTransformedReceivedMessageTuple.getT2() here
                        .map(oneTransformedReceivedMessageTuple -> SenderRecord.create(new ProducerRecord<>("CHANGE_TOPIC_DESTINATION", null, oneTransformedReceivedMessageTuple.getT1()), oneTransformedReceivedMessageTuple.getT1()))
                )
                ;
    }
```

**Comment by artembilan** [comment]
Yeah... It won't be available there anyway. Because `kafkaSender.send()` is not a part of that "observed" action.
So, sorry: I take back my first proposal.
In your current 
```
kafkaSender.send(
                this.kafkaReceiver
                        .receive())
```
combination you cannot propagate internally received observation to top level.
That's the way how Reactor context work: it goes from bottom to top on subscribe, not when we publish events from top to bottom.

**Comment by patpatpat123** [comment]
Understood, so first solution is out.
So, for solution 2:

**Comment by artembilan** [comment]
Well, you got the idea.
I suggested to use `KafkaSender.createOutbound()` upfront and then its `kafkaOutbound.send().then()` in the `flatMap()` instead of `kafkaSender.send()` with that strange `map()`.
My apologies, but this is just wild guess how it can work for your expectation: I really don't have any field experience with this observation propagation.
I'm also not sure in your `tap()` though. If you already have an observation in hands, why create a new one?

You may also try just `kafkaOutbound.send()` in the `doOnNext()` (or `handle()`) instead.
And then add `kafkaOutbound.subscribe()` as a part of your top-level `Flux.doOnSubscribe()`.

It is too much for me to try to come up with some working example for your use-case.
Probably your `receive-n-publish` scenario doesn't fit into our current publisher-subscriber observation propagation model.
And it has to be implemented some other way...

**Comment by patpatpat123** [comment]
This is quite unfortunate.

Solution 1, which is out of the picture now, was kind of my only hope.

Solution 2 has been proven less performant in temrs of speed, and also in terms of readability.
As you mentionned, this is very intuitive 
```
kafkaSender.send(
                this.kafkaReceiver
                        .receive())
```

Kinda stuck here. But if not anything, thank you for looking into this

**Comment by artembilan** [comment]
Another observation for this scenario.
You want to publish the whole `Flux` of records, but at the same time you want an observation per records.
That's really not how Reactor context and its scope works. I
It is per reactive stream, therefore it is not a surprise to see that those spans for records are part of the same parent trace. Just because this parent for that `Flux` you try to publish as a unit.

You may handle that yourself with some custom `Observation` on each record producing but already before it has reached the publisher.
I mean, for your expectations, an observation config on the sender does not make sense.

Hope this clears things a little bit...

**Comment by patpatpat123** [comment]
Thank you Artem. Good day!
