### ISSUE TITLE
Downstream performance issue

### ISSUE THREAD

**Issue by gzeskas** [reactor/reactor-kafka#45]
I'm writing an application that is reading from kafka topic, using this reactive-kafka driver and saving all received records to cassandra using spring-reactive-kafka driver.

When I have a simple workflow like just receive record and write it cassandra using flatMap function my performance is very near to optimal, but when for example I in introduce one additional reactive operator like simple filter performance is dropped twice.

When I add this synthetic filter just for test my performance of completed cassandra operations drops twice. 

For example if my cluster can handle 100k w/s and after adding this filter operation only 50k w/s is made.

```java
KafkaReceiver.create(options).receiveAutoAck()
                .concatMap(consumerRecordFlux -> consumerRecordFlux.map(record -> record.value().get()))
                .doOnNext(m -> incomingMessageCounter.incrementAndGet())
                .filter(bytes -> incomingMessageCounter.get() % 5 == 0)
                .flatMap(bytes -> cassandra.simpleInsert(bytes))
                .subscribe(m -> {
                    completedMessageCounter.getAndIncrement();
                });
```

write to cassandra is very simple:

```java
    public Flux<Boolean> simpleInsert(Integer id) {
        return reactiveCqlOperations.execute(insertPSC, new ReactivePreparedStatementCallback<ReactiveResultSet>() {
            @Override
            public Publisher<ReactiveResultSet> doInPreparedStatement(ReactiveSession session, PreparedStatement ps) throws DriverException, DataAccessException {
                BoundStatement boundStatement = ps.bind()
                        .setInt("id", id)
                        .setString("name", "name:"+id);
                boundStatement.setConsistencyLevel(ConsistencyLevel.ANY);
                return session.execute(boundStatement);
            }
        }).map(ReactiveResultSet::wasApplied);
    }
```
Maybe I should do work like this in another manner ?

**Comment by OlegDokuka** [comment]
Hey @gzeskas, I tend to think that in your case the performance degradation is because the part of the messages are filtered so instead of all messages / per second you receive, suppose, half of them, thus there is a filling that there is a performance issue. I would suggest you run the test where all messages bypass the filter so you will receive all messages as it would be without a `filter`.

I will close the issue since from my point it is not related to Reactor-Kafka itself and in the worst case maybe a Reactor issue instead.
