### ISSUE TITLE
Springboot-like autoconfiguration

### ISSUE THREAD

**Issue by gAmUssA** [reactor/reactor-kafka#64]
Are there any plans to support springboot-like autoconfiguration using `application.yml` or `application.properties`?

**Comment by simonbasle** [comment]
No plan, I don't think it should be a goal of the project to attempt at providing (auto)configuration to the level of what Spring Boot does.

Rather, it would make more sense if someone contributes a starter to Spring Boot.

That said, if such an integration proves difficult due to missing pieces in reactor-kafka we should consider making the necessary improvements.

**Comment by garyrussell** [comment]
I think it would be quite easy to extend the current Spring autoconfiguration for Kafka to create `KafkaSender` and `ReceiverOptions` beans from the existing boot `KafkaProperties`.

@gAmUssA perhaps open an issue against boot?

**Comment by hartmut-co-uk** [comment]
WIP.. see https://github.com/spring-projects/spring-kafka/pull/559
