### ISSUE TITLE
max.poll.interval.ms to be set to infinite (Integer.MAX_VALUE) as default. 

### ISSUE THREAD

**Issue by maitreyak** [reactor/reactor-kafka#96]
If any of reactor-kafka flux subscribers introduce a delay or exponential backoff, PollEvents are no longer emitted. 

f the delay is greater than _max.poll.interval.ms_ the underlying Kafka consumer times out and trigger's a rebalance. 

For a reactor client shouldn't the _max.poll.interval.ms_ be set to infinite (Integer.MAX_VALUE)?

**Comment by mangan77** [comment]
I second this opinion. Slow consumption of events leads to unwanted errors or forcing pre-mature ACK of events.

**Comment by AdamDev84** [comment]
This is not a solution but workaround.
Kafka cosumer client has method consumer.pause() to pause retrieving new records from topic but still it allows to call poll. The ability to call poll is very important it should be called in some loop or in interval flux like for CommitEvent is has been done.

Kafka is using poll method to gather all members of the group and rebalance partitions so it has to be called quite frequently.

I wanted to use this extension in my project but because of this limitation I had to give up on this. 

I hope you will solve this issue in a proper way.

**Comment by bsideup** [comment]
Kafka consumers should poll regularly, otherwise they will be de-assigned from the group.
